### ISSUE TITLE
[BUG GGT_CLI_UNEXPECTED_ERROR]: 

### ISSUE THREAD

**Issue by danroberts** [gadget-inc/ggt#255]
### Description
[Please describe what you were doing when this error occurred]

### Command
```sh-session
ggt sync --app radical-react /Users/droberts/gadget/radical-react
```

### Environment
```
version: 0.0.0-alpha.8
platform: darwin
arch: arm64
shell: zsh
timestamp: 2023-02-10T18:17:17.964Z
```

### Stack Trace
```
Error: An unexpected error occurred
    at Sync.catch (/Users/droberts/.npm/_npx/8983d659e91601aa/node_modules/@gadgetinc/ggt/dist/lib/base-command.js:136:69)
    at Sync._run (/Users/droberts/.npm/_npx/8983d659e91601aa/node_modules/@gadgetinc/ggt/node_modules/@oclif/core/lib/command.js:77:29)
    at async Config.runCommand (/Users/droberts/.npm/_npx/8983d659e91601aa/node_modules/@gadgetinc/ggt/node_modules/@oclif/core/lib/config/config.js:270:25)
    at async Object.run (/Users/droberts/.npm/_npx/8983d659e91601aa/node_modules/@gadgetinc/ggt/node_modules/@oclif/core/lib/main.js:76:5)
```
### Cause
```json
{
  "name": "HTTPError",
  "code": "ERR_NON_2XX_3XX_RESPONSE",
  "timings": {
    "start": 1676053037739,
    "socket": 1676053037740,
    "lookup": 1676053037742,
    "connect": 1676053037758,
    "secureConnect": 1676053037780,
    "upload": 1676053037780,
    "response": 1676053037959,
    "end": 1676053037962,
    "phases": {
      "wait": 1,
      "dns": 2,
      "tcp": 16,
      "tls": 22,
      "request": 0,
      "firstByte": 179,
      "download": 3,
      "total": 223
    }
  },
  "message": "Response code 401 (Unauthorized)",
  "stack": "HTTPError: Response code 401 (Unauthorized)\n    at Request.<anonymous> (/Users/droberts/.npm/_npx/8983d659e91601aa/node_modules/@gadgetinc/ggt/node_modules/got/dist/source/as-promise/index.js:118:42)\n    at processTicksAndRejections (node:internal/process/task_queues:96:5)"
}
```

**Comment by scott-rc** [comment]
Bruh 🤣  
> version: 0.0.0-alpha.8
